defalut: main.c
	@printf "\033[1;33mgcc\033[0m \033[1;36m./rename_pwd.c\033[0m \033[1;33m-o\033[0m \033[1;35m~/Desktop/programming/system_script/co\033[0m\n" 
	@gcc main.c -o ~/Desktop/programming/system_script/co

move: main.c makefile
	cp ./main.c ~/Desktop/programming/git_repositories/my_config/global/compile/main.c	
	cp ./makefile ~/Desktop/programming/git_repositories/my_config/global/compile/makefile
