defalut: main.c
	gcc main.c -o ~/Desktop/programming/system_script/co

move: main.c makefile
	cp ./main.c ~/Desktop/programming/git_repositories/my_config/global/compile/main.c	
	cp ./makefile ~/Desktop/programming/git_repositories/my_config/global/compile/makefile
