defalut: main.c
	@printf "\033[1;33mgcc\033[0m \033[1;36m./main.c\033[0m \033[1;33m-o\033[0m \033[1;35m~/Developer/system_script/co\033[0m\n" 
	@gcc ./main.c -o ~/Developer/system_script/co 

move: main.c makefile
	cp ./main.c ~/Developer/git_repositories/my_config/global/compile/main.c	
	cp ./makefile ~/Developer/git_repositories/my_config/global/compile/makefile
