ide = ["CLion",
	"JupterNoteBook",
	"SublimeText",
	"VisualStudioCode",
	"VisualStudio",
	"PyCharm",
	"IntelliJ",
	"Xcode",
	"AndroidStudio",
	"Eclips",
	"NotepadPP",
]

language = ["C",
	"C++",
	"C#",
	"Java",
	"Rust",
	"Python",
]
